version: '3'
services:
  app:
    build: .
    container_name: node_app
    working_dir: /app
    ports:
      - "8080:8080" 
    networks:
      - mynetwork
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork

networks:
  mynetwork:
